EP_SWD62B_20252026/Presentation/Controllers/BooksController.cs
using DataAccess.Repositories;
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Presentation.Models;

namespace Presentation.Controllers
{
    public class BooksController : Controller
    {
        //Constructor Injection is one of the variations of Dependency Injection.
        private BooksRepository _booksRepository { get; set; }

        public BooksController(BooksRepository booksRepository)
        {
            this._booksRepository = booksRepository;
        }

        //Method Injection - Use [FromServices] BooksRepository _booksRepository in the parameter list.

        [HttpGet]
        public IActionResult Index()
        {
            /* IQueryable - prepares an SQL statement. 
             * ToList<> or AsEnumerable() - open a connection with the database. 
             * When you run ToList(), it also enables you to inspect the data. */
            List<Book> books = this._booksRepository.Get().ToList();
            return View(books); //A call will be initiated with the database.
        }

        [HttpPost]
        public IActionResult Index(string keyword)
        {
            List<Book> filteredList = this._booksRepository.Get(keyword).ToList();
            return View(filteredList);
        }

        public IActionResult Details(int id)
        {
            Book book = this._booksRepository.Get(id);
            return View(book);
        }

        [HttpGet] //Loads and renders a page with empty input controls.
        public IActionResult Create([FromServices] CategoriesRepository categoriesRepository)
        {
            /* BooksCreateViewModel 
             * - Book entity
             * - List of categories */

            //Fetched list of categories passed to the page.
            BooksCreateViewModel booksCreateViewModel = new BooksCreateViewModel();
            booksCreateViewModel.Categories = categoriesRepository.Get().ToList(); //A call to the database is done upon invoking ToList().
            return View(booksCreateViewModel); //Use a ViewModel as a carrier of data to the view.
        }

        [HttpPost] //Handles the submission form.

        /* We refer to services being injected as either Application Services or Framework Services. 
         * Application Services: CategoriesRepository (injecting user-defined classes that act as services that we have created ourselves)
         * Framework Services: IWebHostEnvironment (built-in services provided by .NET Core) */
        public IActionResult Create(BooksCreateViewModel booksCreateViewModel, [FromServices] CategoriesRepository categoriesRepository, [FromServices] IWebHostEnvironment host) //The model has to match the one being expected.
        {
            try
            {
                //We need to receive the image.
                if(booksCreateViewModel.UpdatedFile != null)
                {
                    //We have a file...

                    //File needs to be saved.
                    string uniqueFilename = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(booksCreateViewModel.UpdatedFile.FileName);
                    string absolutePath = Path.Combine(host.WebRootPath, "images", uniqueFilename);

                    //FileStream is one of the methods available to save files into a server.
                    using(FileStream fileStream = new FileStream(absolutePath, FileMode.CreateNew))
                    {
                        booksCreateViewModel.UpdatedFile.CopyTo(fileStream);
                        fileStream.Flush();
                        fileStream.Close();
                    }

                    booksCreateViewModel.Book.Path = Path.DirectorySeparatorChar + Path.Combine("images", uniqueFilename);
                }

                /* Ways how you can pass data from the server side (i.e. controller) to the client side (i.e. views):
                 * - TempData = It survives a redirection (if I redirect the user to Index page instead, TempData is still accessible)
                 * - ViewData or ViewBag = They are fine if there is no redirection and data is lost after you pass it to the page.
                 *    - ViewBag.success = "Book created successfully";
                 *    - ViewData["success"] = "Book created successfully";
                 * - Session = In session, whatever you store survives many redirections until the user logs out or until the user leaves the account unattended for x minutes.
                 * - Cookies = Cookies are files stored in the client browser - they may be used to store data BUT be careful - cookies are not encrypted.
                 * - Models = So we can edit the Book class, add a property called Feedback and we set it with the data we want to pass back to the page. */

                this._booksRepository.Add(booksCreateViewModel.Book);
                TempData["success"] = "Book created successfully.";
                return RedirectToAction(nameof(Create)); //Return a redirection where the request came from with no data related to the book - prevents reinstantiating BooksCreateViewModel and repopulating list of categories.
            }
            catch (Exception exception)
            {
                booksCreateViewModel.Categories = categoriesRepository.Get().ToList();
                TempData["failure"] = "Error occurred - Book was not saved. Try again, we are working on it.";
                return View(booksCreateViewModel); //Loading back the view where the request came from with the submitted data.
            }
        }

        [HttpGet]
        public IActionResult Update(int id, [FromServices] CategoriesRepository categoriesRepository) 
        {
            BooksCreateViewModel booksCreateViewModel = new BooksCreateViewModel();
            booksCreateViewModel.Categories = categoriesRepository.Get().ToList(); //A call to the database is done upon invoking ToList().
            booksCreateViewModel.Book = this._booksRepository.Get(id);
            return View(booksCreateViewModel);
        }

        [HttpPost]
        public IActionResult Update(BooksCreateViewModel booksCreateViewModel, [FromServices] CategoriesRepository categoriesRepository) 
        {
            try
            {
                TempData["success"] = "Book update successfully.";

                this._booksRepository.UpdateBook(booksCreateViewModel.Book);
                return RedirectToAction(nameof(Update), new { id = booksCreateViewModel.Book.Id });
            }
            catch (Exception exception)
            {
                booksCreateViewModel.Categories = categoriesRepository.Get().ToList();
                TempData["failure"] = "Error occurred - Book was not saved. Try again, we are working on it."; //Log the error.
                return View(booksCreateViewModel);
            }
        }

        public IActionResult Delete(int id)
        {
            this._booksRepository.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Delete(int[] ids)
        {
            try
            {
                foreach (int id in ids)
                {
                    this._booksRepository.Delete(id);
                }

                TempData["success"] = "Book(s) deleted successfully!";
            }
            catch(Exception exception)
            {
                TempData["failure"] = "Books were not deleted. Try again!";
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

EP_SWD62B_20252026/Presentation/Controllers/TestController.cs
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using Presentation.Models;

namespace Presentation.Controllers
{
    public class TestController : Controller
    {
        public IActionResult Index()
        {
            TestModel testModel = new TestModel()
            {
                Author = User.Identity.IsAuthenticated ? User.Identity.Name : "Me",
                Message = "This is a test. Welcome to ASP.NET Core site.",
                DatePublished = DateTime.Now
            };

            return View(testModel);
        }

        public IActionResult SubmitForm(TestModel data)
        {
            if (data != null)
            {
                //Process the data.
                if (!string.IsNullOrEmpty(data.Message))
                {
                    int wordCount = data.Message.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries).Length; //Do not count empty entries.
                    ViewBag.WordCount = wordCount;
                }

                if(!string.IsNullOrEmpty(data.Author))
                {
                    data.Author = data.Author.ToUpper();
                }
                
                data.DatePublished = DateTime.Now;

                return View(nameof(Index), data); //Otherwise, by default, the controller will attempt to redirect the user to a view named SubmitForm which does not exist.
            }

            return View(nameof(Index));
        }
    }
}

EP_SWD62B_20252026/Presentation/Views/Shared/_FeedbackPartial.cshtml
@{
    var success = TempData["success"] as string;
    var error = TempData["failure"] as string;
    var info = TempData["info"] as string;

    var message = success ?? error ?? info;
    var type = success != null ? "success" : error != null ? "danger" : info != null ? "info" : null;
    var title = success != null ? "Success" : error != null ? "Error" : info != null ? "Notice" : null;
}

@if (!string.IsNullOrEmpty(message) && type != null)
{
    <div class="modal fade" id="feedbackModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header bg-@type text-white">
                    <h5 class="modal-title">@title</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    @message
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-@type" data-bs-dismiss="modal">OK</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var element = document.getElementById('feedbackModal');
            if (element && typeof bootstrap !== 'undefined') {
                new bootstrap.Modal(element).show();
            }
        });
    </script>
}

EP_SWD62B_20252026/Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Presentation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Presentation.styles.css" asp-append-version="true" />
</head>
@await Html.PartialAsync("_FeedbackPartial")
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Presentation</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="Index">Test</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Presentation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>